### ISSUE TITLE
Cursor keeps invisible when default colorscheme (or potentially other colorschemes) is used in Neovim

### ISSUE THREAD

**Issue by Iron-E** [lambdalisue/fern.vim#177] opened 2020-08-24 20:25 UTC
# Description

Hello, thank you for this plugin! It's been a great alternative to NERDTree for me.

A few days ago I started to experience my cursor disappearing after I enter a `fern` buffer.

# Steps to Reproduce

1. Use the `:Fern` command.
2. Notice your cursor is now invisible, although exists.
    * You can edit a file and the cursor will still be invisible.

Manually setting the buffer type to `fern` using `:setf` doesn't reproduce the bug.

# Attempts to Workaround

I have tried the following things to see if they resolve the issue (to no success):

* Changing colorschemes / clearing the cursor's highlight group.
    * Additionally, running `highlight cursor` shows that the cursor's highlight group is correctly set.
* Entering a file from a `fern` buffer.

The only way to fix is by restarting Vim.

# Vim Information

I am using the latest Neovim 0.5 nightly.

**Comment by lambdalisue** [comment] 2020-08-25 01:31
I need to read and investigate but for quick workaround. You can disable that feature by https://github.com/lambdalisue/fern.vim/blob/master/doc/fern.txt#L378 in case you haven't noticed it.

**Comment by Iron-E** [comment] 2020-08-25 16:04
The cursor is supposed to stay invisible even after I leave a `fern` buffer and begin to edit a file? Just so I'm sure we're on the same page— the issue isn't that the cursor is hidden while in the `fern` buffer (I like that feature!), it's that it stays hidden while editing text after having been in a `fern` buffer until I restart Vim.

I set the variable for the meantime.

---

For posterity, I tried this feature in Neovim 0.4.3 and it behaves differently. Instead of disappearing, the cursor turns into a bar, which persists after leaving Vim and into my terminal. 

On both versions the cursor is not restored, although the _way_ in which the cursor is not restored is different.

**Comment by lambdalisue** [comment] 2020-08-26 00:07
> On both versions the cursor is not restored, although the way in which the cursor is not restored is different.

That's sound an unexpected behavior. In my environment, the cursor is restored on Vim/Neovim. Please provide your environment information and **minimal** vimrc and **minimal** steps to reproduce so that I can investigate.

**Comment by lambdalisue** [comment] 2020-08-26 03:48
I'd also like to know what happens if you execute [`:call fern#internal#cursor#restore()`](https://github.com/lambdalisue/fern.vim/blob/master/autoload/fern/internal/cursor.vim#L8-L10) manually after the cursor disappeared. If the cursor does not appear again, the function has some bug. If the cursor is appeared, [`BufLeave,WinLeave,CmdwinEnter,CmdlineEnter`](https://github.com/lambdalisue/fern.vim/blob/master/autoload/fern/internal/viewer.vim#L62) are not invoked.

**Comment by lambdalisue** [comment] 2020-08-26 10:18
It seems the following settings in Vim cause it?

```
set cursorlineopt=number
```

**Comment by Iron-E** [comment] 2020-08-26 17:13
Here's a minimal configuration which reproduces the bug for me:

```vim
set termguicolors         " Set color mode

call plug#begin(expand("~/.local/share/nvim/plugged"))
	Plug 'https://github.com/lambdalisue/fern.vim.git'
call plug#end()
```

`:call fern#internal#cursor#restore()` doesn't restore the cursor, although I _did_ notice that unless I used `termguicolors` everything worked perfectly.

**Comment by lambdalisue** [comment] 2020-08-27 01:39
Thanks. The behavior has reproduced with `set termguicolors` on Neovim 0.5.0. I'll investigate 👍

**Comment by lambdalisue** [comment] 2020-08-27 15:41
It seems the default `Cursor` highlight `xxx guifg=bg guibg=fg` does NOT work and `set guicursor+=a:Cursor/lCursor` is just ignored. So that we cannot restore cursor when `termguicolors` is enabled on **default** colorscheme.

https://github.com/neovim/neovim/issues/6508#issuecomment-294253742

**Comment by lambdalisue** [comment] 2020-08-27 15:48
@Iron-E Please try #180

**Comment by Iron-E** [comment] 2020-08-27 16:59
Thanks for the branch! The cursor doesn't appear to be restored, although I wonder if this could be an issue with Neovim.

I can't seem to set the cursor's highlight group to _anything_, even with `nvim -u NORC -c 'set termguicolors'`. I did more reading on junegunn/seoul256#41 and it seems like others are having trouble getting Neovim to behave properly in this way too. Perhaps I should open a ticket there referencing this?

**Comment by lambdalisue** [comment] 2020-08-28 00:29
@Iron-E Could you try if the following fix the issue on the current `master` (not #180)?

```vim
highlight Cursor cterm=reverse gui=reverse
```

**Comment by Iron-E** [comment] 2020-08-28 16:59
After setting `Plug` back to the `master` branch the `highlight` command doesn't affect it.

My colorscheme actually uses those settings for the `Cursor` highlight group too.

**Comment by Iron-E** [comment] 2020-08-28 17:52
I cloned the repo and started poking around inside of the `#restore()` function, and found that if I make Vim `sleep` for a few milliseconds, the `Cursor` comes back. I'll issue a PR to merge if the solution is adequate

**Comment by lambdalisue** [comment] 2020-08-29 03:15
> After setting Plug back to the master branch the highlight command doesn't affect it. For posterity I went through and tried to run the Neovim FAQ procedure for changing cursor colors and it didn't restore it either.
>
> My colorscheme actually uses those settings for the Cursor highlight group too.

Hum... Then I think we are facing different issues. You have to make sure that [Neovim FAQ procedure](https://github.com/neovim/neovim/wiki/FAQ#how-to-change-cursor-color-in-the-terminal) works on your environment.

**Comment by lambdalisue** [comment] 2020-08-31 02:57
I closed this issue because

- The default scheme issue is on Neovim side. We should not apply any patch for that
- If [Neovim FAQ procedure](https://github.com/neovim/neovim/wiki/FAQ#how-to-change-cursor-color-in-the-terminal) didn't work, the issue is on Neovim side thus fern.vim should not apply any patch for that

**Closed by lambdalisue** 2020-08-31 02:57 UTC
Labels: bug (Neovim), wontfix
